:toc: macro


toc::[]


= Usage

Should work best (ie more predictible) if you suffix your scm urls with ".git" (so we know exactly where to truncate).
This is helpfull because a not-so-known "feature" of Maven is that every child modules sees it's artifactId appended at the end of
the scm urls declared in it's parent pom :/

Id does not display the FULL tree because we only got the 'resolved' dependencies. This means that if A->B->C and A->C we 
will not see B->C in the graph. For more info, refere to the dependency:tree plugin and it's comments regarding the "verbose"
flag ("To fix we probably need a different DependencyCollector in Aether, which doesn't remove nodes which have already been resolved.").

= TODO

* detect git cycles
* use special color for specific vertex (for exemple SCMRepo with no scm tag defined should be red ?)
* add this plugin in all builds and to Jenkins JenkinsFile to be archived on each build
* test with "Maven Invoker Plugin" instead of the fucked up maven-plugin-testing-harness...
* we could encapsulate in the graph all the dependencies belonging to a given repo. It would give us
a classic maven dependency graph, but with dependencies groupped by their repo from origin

= DONE
* removed some pattern from being displayed in Graph (such as gitlab.xxx-yyy.local:)
* remove JGtaphT and use only JGraphX
